name: CI/CD Pipeline - Saudacoes Aleatorias

on:
  push:
    branches: [ "main" ]

jobs:
  build-lint:
    name: ğŸ” Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Install golangci-lint (local)
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ./bin v1.53.3

      - name: Run linter
        run: ./bin/golangci-lint run ./...
